package practica12;

import java.awt.Cursor;
import GraphicsBasico2D.Config;
import UI.CanvasImage;

/**
 * Esta clase representa una ventana interna
 * @author Adri
 */
public class InternalWindow extends javax.swing.JInternalFrame
{

    private MainWindow parent;

    /**
     * Creates new form VentanaInterna
     */
    public InternalWindow()
    {
        initComponents();
    }

    /**
     *
     * @return
     */
    public CanvasImage getCanvas()
    {
        return this.canvas;
    }

    /**
     * Establece el padre de la ventana
     * @param w la instancia de MainWindow
     */
    public void setParent(MainWindow w)
    {
        this.parent = w;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        canvas = new UI.CanvasImage();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(200, 200));
        setPreferredSize(new java.awt.Dimension(600, 400));

        javax.swing.GroupLayout canvasLayout = new javax.swing.GroupLayout(canvas);
        canvas.setLayout(canvasLayout);
        canvasLayout.setHorizontalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );
        canvasLayout.setVerticalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );

        jScrollPane.setViewportView(canvas);

        getContentPane().add(jScrollPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Controla cuando el rat�n ha entrado en el lienzo para pintar la posici�n
     * @param evt el evento del rat�n
     */
    private void canvasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseMoved

        this.parent.setCursorPosition("(" + evt.getX() + "," + evt.getY() + ")");

        if (Config.GENERALCONFIG.getSelectedTool() == Config.Tool.HAND)
            this.setCursor(new Cursor(java.awt.Cursor.MOVE_CURSOR));
        else
            this.setCursor(new Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

    }//GEN-LAST:event_canvasMouseMoved
    
    /**
     * Controla cuando el rat�n ha salido del lienzo para dejar de pintar la posici�n
     * @param evt el evento del rat�n
     */
    private void canvasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseExited
        this.parent.setCursorPosition("(x,y)");
        this.setCursor(new Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_canvasMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private UI.CanvasImage canvas;
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration//GEN-END:variables
}