package practica7;

import java.awt.Cursor;
import java.io.File;
import GraphicsBasico2D.Config;
import UI.CanvasImage;

/**
 *
 * @author Adri
 */
public class InternalWindow extends javax.swing.JInternalFrame {

    private MainWindow parent;
    
    /**
     * Creates new form VentanaInterna
     */
    public InternalWindow() {
        initComponents();
    }

    public InternalWindow(File f) {
        initComponents();

    }

    public CanvasImage getCanvas()
    {
        return this.canvas;
    }
    
    public void setParent(MainWindow w)
    {
        this.parent = w;
    }
    public MainWindow getParent()
    {
        return this.parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        canvas = new UI.CanvasImage();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(200, 200));
        setPreferredSize(new java.awt.Dimension(600, 400));

        canvas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canvasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                canvasMouseExited(evt);
            }
        });
        canvas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                canvasMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout canvasLayout = new javax.swing.GroupLayout(canvas);
        canvas.setLayout(canvasLayout);
        canvasLayout.setHorizontalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );
        canvasLayout.setVerticalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );

        jScrollPane.setViewportView(canvas);

        getContentPane().add(jScrollPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void canvasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseMoved
        int x = evt.getX()-8;
        int y = evt.getY()-89;
        this.parent.setCursorPosition("(" + x + "," + y + ")");  
        
        if ( Config.GENERALCONFIG.getSelectedTool() == Config.Tool.HAND  )       
            this.setCursor(new Cursor(java.awt.Cursor.MOVE_CURSOR));
        else if ( Config.GENERALCONFIG.getSelectedTool() == Config.Tool.SELECT  )       
            this.setCursor(new Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));
        else
            this.setCursor(new Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));               
        
    }//GEN-LAST:event_canvasMouseMoved

    private void canvasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseExited
        this.parent.setCursorPosition("(x,y)");   
        this.setCursor(new Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_canvasMouseExited

    private void canvasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseClicked
        if ( (Config.GENERALCONFIG.getSelectedTool() == Config.Tool.SELECT || Config.GENERALCONFIG.getSelectedTool() == Config.Tool.HAND )&& this.canvas.getSelectedShape(evt.getPoint()) != null ) {
            this.parent.setSelectedShape(this.canvas.getSelectedShape(evt.getPoint()));
            this.getCanvas().setSelectedShape(this.canvas.getSelectedShape(evt.getPoint()));
        }
    }//GEN-LAST:event_canvasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private UI.CanvasImage canvas;
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration//GEN-END:variables
}
