/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica4;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;

/**
 *
 * @author Adri
 */
public class Lienzo extends javax.swing.JPanel {

    Point pIni;
    Point pFin;
    Point pClick;
    Color color = Color.BLACK;
    Forma forma = Forma.PUNTO;
    boolean relleno = false;
    
    /**
     * Creates new form Lienzo
     */
    public Lienzo() {
        initComponents();
    }
    
    @Override
    public void paint (Graphics g){
        super.paint(g);
        g.setColor(this.color);
        
        switch (forma){
            case PUNTO: {
                if( this.pClick == null) { break; }
                g.fillOval(this.pClick.x - 2, this.pClick.y - 2, 4, 4);
                break;
            }
            case LINEA: {
                if( this.pIni == null || this.pFin == null) { break; }
                g.drawLine(this.pIni.x, this.pIni.y, this.pFin.x, this.pFin.y);
                break;
            }
            case RECTANGULO: {
                if( this.pIni == null || this.pFin == null) { break; }
                int x = Math.min(this.pIni.x, this.pFin.x);
                int y = Math.min(this.pIni.y, this.pFin.y);
                int ancho = Math.abs(this.pIni.y - this.pFin.y);
                int alto = Math.abs(this.pIni.x - this.pFin.x);
                
                if (this.relleno) {
                    g.fillRect(x, y, alto, ancho);
                    break;
                }
                g.drawRect(x, y, alto, ancho);
                break;
            }
            case ELIPSE: {
                if( this.pIni == null || this.pFin == null) { break; }
                int x = Math.min(this.pIni.x, this.pFin.x);
                int y = Math.min(this.pIni.y, this.pFin.y);
                int ancho = Math.abs(this.pIni.y - this.pFin.y);
                int alto = Math.abs(this.pIni.x - this.pFin.x);
                
                if (this.relleno) {
                    g.fillOval(x, y, alto, ancho);
                    break;
                }
                g.drawOval(x, y, alto, ancho);
                break;
            }
        }
    }
    
    public void clearPoints(){
        this.pFin = null;
        this.pIni = null;
        this.pClick = null;
    }
    
    public void setColor(Color color){
        this.color = color;
    }
    
    public Color getColor(){
        return color;
    } 
    
    public Forma getForma() {
        return forma;
    }

    public void setForma(Forma forma) {
        this.forma = forma;
    }
    
    public boolean isRelleno() {
        return relleno;
    }

    public void setRelleno(boolean relleno) {
        this.relleno = relleno;
    } 
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        this.pClick = evt.getPoint();
        this.repaint();
    }//GEN-LAST:event_formMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        this.clearPoints(); // Para que las formas no hagan cosas extrañas        
        this.pIni = evt.getPoint();
        this.repaint();
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        this.pFin = evt.getPoint();
        this.repaint();
    }//GEN-LAST:event_formMouseReleased

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        this.pFin = evt.getPoint();
        this.repaint();
    }//GEN-LAST:event_formMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
